### ISSUE TITLE
ImportError: No module named tspinput

### ISSUE THREAD

**Issue by anindyasadhu** [rshipp/tsp#1]
ImportError                               Traceback (most recent call last)
<ipython-input-11-9e5a7dac4f0b> in <module>()
     43 import timeit
     44 
---> 45 import tspinput
     46 
     47 RUNS = 3

ImportError: No module named tspinput

**Comment by rshipp** [comment]
Please review the instructions in the readme. The `./` is important, the commands must be run in the same folder where the files are downloaded.
